version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - mongo_data:/data/db   # Volume pour persister la base MongoDB

  migration:
    build: .
    container_name: healthcare-migration
    depends_on:
      - mongodb
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - CSV_FILE=/data/ready_healthcare_dataset.csv
    volumes:
      - ./data:/data   # Volume pour stocker et partager ton CSV avec le conteneur

volumes:
  mongo_data: